# Generated by Django 5.1 on 2024-10-17 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctitle',
            name='type',
            field=models.CharField(choices=[('student_details', 'Student Details'), ('fee_payment', 'Fee Payment')], default='student_details', max_length=20),
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_paid', models.DateField()),
                ('doc_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='portal.doctitle')),
            ],
        ),
    ]
