# Generated by Django 4.2.16 on 2025-01-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_alter_results_subject_alter_results_term_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payfee',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_fee_records', to='portal.term'),
        ),
    ]
