# Generated by Django 4.2.16 on 2025-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_payfee_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='payfee',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
