# Generated by Django 4.2.16 on 2024-12-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_feepayment_balance_feepayment_student_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctitle',
            options={'verbose_name_plural': 'Document Title'},
        ),
        migrations.AlterModelOptions(
            name='studentdet',
            options={'verbose_name_plural': 'Student Details'},
        ),
        migrations.AlterUniqueTogether(
            name='studentdet',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='studentdet',
            name='doc_title',
        ),
    ]
