# Generated by Django 4.2.16 on 2024-12-30 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_alter_doctitle_options_alter_studentdet_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctitle',
            options={'verbose_name_plural': 'Documents'},
        ),
    ]
