# Generated by Django 4.2.16 on 2025-01-02 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_classlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassLevel',
        ),
    ]
