# Generated by Django 4.2.16 on 2024-12-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdet',
            name='grade',
            field=models.CharField(choices=[('playgroup', 'Playgroup'), ('pp1', 'pp1'), ('pp2', 'pp2'), ('pp3', 'pp3'), ('pp4', 'pp4'), ('pp5', 'pp5'), ('pp6', 'pp6'), ('pp7', 'pp7'), ('pp8', 'pp8'), ('grade1', 'grade 1'), ('grade2', 'grade 2'), ('grade3', 'grade 3'), ('grade4', 'grade 4'), ('grade5', 'grade 5'), ('grade6', 'grade 6'), ('grade7', 'grade 7'), ('grade8', 'grade 8')], default='playgroup', max_length=20),
        ),
        migrations.DeleteModel(
            name='FeePayment',
        ),
    ]
