# Generated by Django 4.2.16 on 2024-12-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_studentdet_grade_delete_feepayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdet',
            old_name='grade',
            new_name='class_name',
        ),
    ]
