# Generated by Django 4.2.16 on 2025-01-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_classlevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classlevel',
            name='term_fee',
        ),
        migrations.RemoveField(
            model_name='classlevel',
            name='year',
        ),
    ]
