# Generated by Django 4.2.16 on 2025-01-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_remove_classlevel_term_fee_remove_classlevel_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdet',
            name='class_name',
        ),
        migrations.AddField(
            model_name='studentdet',
            name='class_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
