# Generated by Django 4.2.16 on 2024-12-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_rename_grade_studentdet_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average'), ('Poor', 'Poor')], default='Good', help_text='Overall health status', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional health notes')),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='portal.studentdet')),
            ],
            options={
                'verbose_name': 'Health Progress',
                'verbose_name_plural': 'Health Progress Records',
                'ordering': ['-date_recorded'],
            },
        ),
    ]
