# Generated by Django 4.2.16 on 2024-12-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_healthprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=100, null=True)),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], default='Term 1', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payment Records',
                'ordering': ['-date_paid'],
            },
        ),
    ]
