# Generated by Django 4.2.16 on 2025-01-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_remove_studentdet_class_name_studentdet_class_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdet',
            name='class_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='portal.classlevel'),
        ),
    ]
