# Generated by Django 4.2.16 on 2024-12-30 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_feepay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepay',
            name='student_name',
        ),
        migrations.AddField(
            model_name='feepay',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='portal.studentdet'),
        ),
    ]
