# Generated by Django 4.2.16 on 2025-01-02 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_alter_studentdet_class_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year', models.DateField(blank=True, null=True)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_fee_records', to='portal.classlevel')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_fee_records', to='portal.term')),
            ],
        ),
    ]
