# Generated by Django 4.2.16 on 2025-01-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_termfee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payfee',
            name='balance',
        ),
    ]
