# Generated by Django 4.2.16 on 2024-12-30 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_remove_feepay_student_name_feepay_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepay',
            name='amount',
        ),
        migrations.AddField(
            model_name='feepay',
            name='amounts',
            field=models.JSONField( default=list, help_text='List of payment amounts', ),
        ),
    ]
