# Generated by Django 4.2.16 on 2025-01-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_payfee_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fee',
        ),
        migrations.DeleteModel(
            name='FeePay',
        ),
    ]
