# Generated by Django 4.2.16 on 2024-12-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_feepay_amount_feepay_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepay',
            name='amounts',
            field=models.JSONField(default=list, help_text='List of payment amounts'),
        ),
    ]
