# Generated by Django 4.2.16 on 2025-01-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_delete_fee_delete_feepay'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_details', to='portal.classlevel')),
            ],
            options={
                'verbose_name_plural': 'Student Details',
            },
        ),
    ]
