# Generated by Django 4.2.16 on 2024-12-31 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_alter_feepay_amounts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=50)),
                ('year', models.PositiveIntegerField(help_text='Year for the term, e.g., 2024')),
                ('transactions', models.JSONField(default=list, help_text='List of transactions with amount and time')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_fee_records', to='portal.studentdet')),
            ],
            options={
                'unique_together': {('std', 'term', 'year')},
            },
        ),
    ]
