# Generated by Django 4.2.16 on 2024-12-31 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_payfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payfee',
            old_name='std',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='payfee',
            unique_together={('student', 'term', 'year')},
        ),
    ]
