# Generated by Django 4.2.16 on 2025-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_studentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/excel_files/'),
        ),
    ]
