# Generated by Django 4.2.16 on 2024-12-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_rename_std_payfee_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payfee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payfee',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payfee',
            name='date_paid',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payfee',
            name='transaction_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='payfee',
            unique_together={('student', 'term', 'date_paid')},
        ),
        migrations.RemoveField(
            model_name='payfee',
            name='transactions',
        ),
        migrations.RemoveField(
            model_name='payfee',
            name='year',
        ),
    ]
