# Generated by Django 4.2.16 on 2025-01-03 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_studentdetails_excel_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentdet',
            options={'verbose_name_plural': 'Student Det'},
        ),
        migrations.RemoveField(
            model_name='studentdetails',
            name='class_level',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_details', to='portal.classlevel'),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='adm_no',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
