# Generated by Django 4.2.16 on 2025-01-03 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_studentdet_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='class_enrolled',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_details', to='portal.classlevel'),
        ),
    ]
