# Generated by Django 4.2.16 on 2024-12-31 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_alter_payfee_unique_together_payfee_amount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payfee',
            unique_together=set(),
        ),
    ]
