# Generated by Django 4.2.16 on 2025-01-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_alter_studentdetails_class_enrolled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='excel_files/'),
        ),
    ]
