# Generated by Django 4.2.16 on 2025-01-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_alter_studentdetails_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_file', models.FileField(blank=True, null=True, upload_to='excel_files/')),
            ],
        ),
    ]
