# Generated by Django 4.2.16 on 2025-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_excelupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
    ]
