# Generated by Django 4.2.16 on 2025-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_delete_excelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='class_enrolled',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
