# Generated by Django 4.2.16 on 2025-01-03 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_excelupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='excel_file',
        ),
    ]
