# Generated by Django 4.2.16 on 2025-01-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0023_remove_studentdetails_excel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='excel_docs/')),
            ],
            options={
                'verbose_name_plural': 'Doc T',
            },
        ),
        migrations.CreateModel(
            name='Std',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=100)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('d_o_b', models.CharField(max_length=10)),
                ('class_enrolled', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Std',
            },
        ),
    ]
