# Generated by Django 4.2.16 on 2025-01-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0024_document_std'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classlevel',
            options={'verbose_name_plural': 'Class , Grade etc'},
        ),
        migrations.AlterModelOptions(
            name='std',
            options={'verbose_name_plural': 'Student Records'},
        ),
        migrations.AlterModelOptions(
            name='termfee',
            options={'verbose_name_plural': 'Fee Per Term'},
        ),
    ]
