# Generated by Django 4.2.16 on 2025-01-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_std_fathers_contact_std_fathers_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='class_enrolled',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='std',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
