# Generated by Django 4.2.16 on 2025-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_alter_std_class_enrolled_alter_std_d_o_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='std',
            name='active_clubs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
