# Generated by Django 4.2.16 on 2025-01-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_std_active_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='d_o_b',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
    ]
