# Generated by Django 4.2.16 on 2025-01-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_alter_std_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='d_o_b',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
