# Generated by Django 4.2.16 on 2025-01-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0030_alter_std_d_o_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='adm_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
