# Generated by Django 4.2.16 on 2025-01-04 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_alter_std_adm_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocTitle',
        ),
        migrations.DeleteModel(
            name='ExcelUpload',
        ),
        migrations.DeleteModel(
            name='StudentDetails',
        ),
    ]
