# Generated by Django 4.2.16 on 2025-01-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0033_health'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFeeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='excel_docs/')),
            ],
            options={
                'verbose_name_plural': 'Fee Upload',
            },
        ),
        migrations.CreateModel(
            name='FeesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_no', models.CharField(max_length=100, unique=True)),
                ('child_name', models.CharField(blank=True, max_length=100, null=True)),
                ('class_enrolled', models.CharField(blank=True, max_length=100, null=True)),
                ('fee_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=100, null=True)),
                ('code_or_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('time_paid', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fees Payment',
            },
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'ordering': ['-date_recorded'], 'verbose_name_plural': 'Health Information'},
        ),
        migrations.AlterField(
            model_name='health',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_information', to='portal.std'),
        ),
    ]
