# Generated by Django 4.2.16 on 2025-01-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0034_excelfeeupload_feespayment_alter_health_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HealthProgress',
        ),
    ]
