# Generated by Django 4.2.16 on 2025-01-04 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0035_delete_healthprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayFee',
        ),
    ]
