# Generated by Django 4.2.16 on 2025-01-05 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0036_delete_payfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('marks', models.PositiveIntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='portal.std')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='portal.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='portal.term')),
                ('term_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_records', to='portal.termsection')),
            ],
        ),
        migrations.DeleteModel(
            name='TermFee',
        ),
    ]
