# Generated by Django 4.2.16 on 2025-01-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0038_remove_studentdet_class_level_delete_results_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Std',
            new_name='Students',
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Students'},
        ),
    ]
