# Generated by Django 4.2.16 on 2025-01-05 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0039_rename_std_students_alter_students_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Student details excel upload'},
        ),
        migrations.AlterModelOptions(
            name='excelfeeupload',
            options={'verbose_name_plural': 'Fee excel Upload'},
        ),
    ]
