# Generated by Django 4.2.16 on 2025-01-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0040_alter_document_options_alter_excelfeeupload_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feespayment',
            options={'verbose_name_plural': 'Fee Records'},
        ),
    ]
