# Generated by Django 4.2.16 on 2025-01-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0041_alter_feespayment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name_plural': 'Student Details'},
        ),
    ]
