# Generated by Django 5.1 on 2024-10-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_doctitle_customuser_studentdet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='auth_user',
        ),
    ]
