# Generated by Django 5.1 on 2024-10-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
    ]
