# Generated by Django 4.2.16 on 2024-12-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='studentadmission',
            options={'verbose_name_plural': 'Student Admission Requests'},
        ),
    ]
