# Generated by Django 4.2.16 on 2025-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_name', models.CharField(max_length=100)),
                ('d_o_b', models.CharField(max_length=10)),
                ('class_enrolled', models.CharField(max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_contact', models.CharField(max_length=100)),
                ('fathers_occupation', models.CharField(max_length=100)),
                ('fathers_location', models.CharField(max_length=100)),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_contact', models.CharField(max_length=100)),
                ('mothers_occupation', models.CharField(max_length=100)),
                ('residential', models.CharField(max_length=100)),
                ('religion', models.CharField(max_length=100)),
                ('guardian_name', models.CharField(max_length=100)),
                ('guardian_contact', models.CharField(max_length=100)),
                ('health_status', models.CharField(max_length=100)),
                ('hospital_recommendation', models.CharField(max_length=100)),
                ('active_clubs', models.CharField(max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Student Admission Requests',
            },
        ),
    ]
