# Generated by Django 4.2.16 on 2025-01-05 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admission',
            options={'verbose_name_plural': 'Admission Requests'},
        ),
    ]
