# Generated by Django 4.2.16 on 2025-01-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_admission_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentAdmission',
        ),
    ]
